basePath: /
consumes:
- application/json
info:
  description: Documentation for a simple coffee shop REST API.
  title: Coffee Shop API.
  version: 1.0.0
paths: {}
produces:
- application/json
schemes:
- http
swagger: "2.0"
